language: python
python:
  - "2.7"
  #- "3.3"
  #- "3.4"
  - "3.5"
env:
  #- TOX_ENV=docs
  #- TOX_ENV=flake8
  #- TOX_ENV=isort
  #- TOX_ENV=pytest
  - TOX_ENV=newloader

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
